 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port  Driver
 *
 * Author: sherif mokhtar 
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = 
{
PORTA_ID,PIN0_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTA_ID,PIN1_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTA_ID,PIN2_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTA_ID,PIN3_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTA_ID,PIN4_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTA_ID,PIN5_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTA_ID,PIN6_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTA_ID,PIN7_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,


PORTB_ID,PIN0_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTB_ID,PIN1_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTB_ID,PIN2_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTB_ID,PIN3_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTB_ID,PIN4_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTB_ID,PIN5_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTB_ID,PIN6_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTB_ID,PIN7_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,


PORTC_ID,PIN0_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTC_ID,PIN1_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTC_ID,PIN2_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTC_ID,PIN3_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTC_ID,PIN4_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTC_ID,PIN5_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTC_ID,PIN6_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTC_ID,PIN7_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,


PORTD_ID,PIN0_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTD_ID,PIN1_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTD_ID,PIN2_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTD_ID,PIN3_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTD_ID,PIN4_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTD_ID,PIN5_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTD_ID,PIN6_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTD_ID,PIN7_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,


PORTE_ID,PIN0_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTE_ID,PIN1_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTE_ID,PIN2_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTE_ID,PIN3_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTE_ID,PIN4_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTE_ID,PIN5_ID,PORT_PIN_IN,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,


PORTF_ID,PIN0_ID,PORT_PIN_IN,PULL_UP,HIGH,DIO_Mode,CHANGEABLE,CHANGEABLE, // this confg is use for this project
PORTF_ID,PIN1_ID,PORT_PIN_OUT,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTF_ID,PIN2_ID,PORT_PIN_OUT,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTF_ID,PIN3_ID,PORT_PIN_OUT,OFF,LOW,DIO_Mode,CHANGEABLE,CHANGEABLE,
PORTF_ID,PIN4_ID,PORT_PIN_IN,PULL_UP,HIGH,DIO_Mode,CHANGEABLE,CHANGEABLE, // this confg is use for this project
};